require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Correo en local: archivo HTML en tmp/letter_opener (gem letter_opener).
  # Así ves el mensaje aunque no tengas SMTP; para Gmail real, sustituye por :smtp y variables en .env.
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.perform_deliveries = true
  config.action_mailer.delivery_method = :letter_opener

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used in links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in the logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in the logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in the logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Jobs sin Redis local (Sidekiq solo fuera de development; ver initializers/sidekiq.rb).
  config.active_job.queue_adapter = :async

  # Permitir dominios ngrok/tunnel para callbacks de Twilio y Meta en desarrollo.
  ngrok_host = ENV.fetch("API_PUBLIC_ORIGIN", "").gsub(%r{^https?://}, "").presence
  config.hosts << ngrok_host if ngrok_host
end
